client
dev tun
proto udp
remote 193.136.212.1 1194
persist-tun
persist-key
ca /etc/pki/CA/ca.crt
cert /etc/pki/CA/client.crt
key /etc/pki/CA/client.key
auth-user-pass
static-challenge "Enter Google Auth Code:" 0
