local 193.136.212.1
port 1194
proto udp
dev tun
ca /etc/pki/CA/ca.crt
cert /etc/pki/CA/vpn.crt
key /etc/pki/CA/vpn.key
dh /etc/openvpn/server/dh2048.pem
server 10.8.0.0 255.255.255.0
push "route 10.60.0.0 255.255.255.0"

plugin /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so "totp login USERNAME password PASSWORD pin OTP"
tls-verify "/etc/openvpn/server/check_ocsp.sh"
tls-export-cert /etc/openvpn/tmp_certs


script-security 2
